Repository ROBOTIS-GIT/physical_ai_tools, pull requests merged in 2025-07, with the labels that each got.

#34 Fixed image streaming and ros client connection issue
  physical_ai_interfaces/CHANGELOG.rst
  physical_ai_interfaces/package.xml
  physical_ai_manager/CHANGELOG.rst
  physical_ai_manager/package-lock.json
  physical_ai_manager/package.json
  physical_ai_manager/src/App.css
  physical_ai_manager/src/App.js
  physical_ai_manager/src/components/ImageGrid.js
  physical_ai_manager/src/components/ImageGridCell.js
  physical_ai_manager/src/components/InferencePanel.js
  physical_ai_manager/src/components/InfoPanel.js
  physical_ai_manager/src/features/ros/rosSlice.js
  physical_ai_manager/src/features/tasks/taskSlice.js
  physical_ai_manager/src/hooks/useRosServiceCaller.js
  physical_ai_manager/src/hooks/useRosTaskStatus.js
  physical_ai_manager/src/pages/InferencePage.js
  physical_ai_manager/src/pages/RecordPage.js
  physical_ai_manager/src/utils/rosConnectionManager.js
  physical_ai_server/CHANGELOG.rst
  physical_ai_server/package.xml
  physical_ai_server/setup.py
  physical_ai_tools/CHANGELOG.rst
  physical_ai_tools/package.xml
Labels: enhancement

#35 Bump 0.5.9
  physical_ai_interfaces/CHANGELOG.rst
  physical_ai_interfaces/package.xml
  physical_ai_manager/CHANGELOG.rst
  physical_ai_manager/package-lock.json
  physical_ai_manager/package.json
  physical_ai_manager/src/App.css
  physical_ai_manager/src/App.js
  physical_ai_manager/src/components/ImageGrid.js
  physical_ai_manager/src/components/ImageGridCell.js
  physical_ai_manager/src/components/InferencePanel.js
  physical_ai_manager/src/components/InfoPanel.js
  physical_ai_manager/src/features/ros/rosSlice.js
  physical_ai_manager/src/features/tasks/taskSlice.js
  physical_ai_manager/src/hooks/useRosServiceCaller.js
  physical_ai_manager/src/hooks/useRosTaskStatus.js
  physical_ai_manager/src/pages/InferencePage.js
  physical_ai_manager/src/pages/RecordPage.js
  physical_ai_manager/src/utils/rosConnectionManager.js
  physical_ai_server/CHANGELOG.rst
  physical_ai_server/package.xml
  physical_ai_server/setup.py
  physical_ai_tools/CHANGELOG.rst
  physical_ai_tools/package.xml
Labels: bump

#41 Support Incremental Video Encoding in Multi-Task Data Recording Mode
  physical_ai_interfaces/CHANGELOG.rst
  physical_ai_interfaces/package.xml
  physical_ai_manager/CHANGELOG.rst
  physical_ai_manager/package-lock.json
  physical_ai_manager/package.json
  physical_ai_server/CHANGELOG.rst
  physical_ai_server/package.xml
  physical_ai_server/physical_ai_server/data_processing/data_manager.py
  physical_ai_server/physical_ai_server/data_processing/lerobot_dataset_wrapper.py
  physical_ai_server/setup.py
  physical_ai_tools/CHANGELOG.rst
  physical_ai_tools/package.xml
Labels: hotfix

#42 Bump 0.5.12
  physical_ai_interfaces/CHANGELOG.rst
  physical_ai_interfaces/package.xml
  physical_ai_manager/CHANGELOG.rst
  physical_ai_manager/package-lock.json
  physical_ai_manager/package.json
  physical_ai_server/CHANGELOG.rst
  physical_ai_server/package.xml
  physical_ai_server/physical_ai_server/data_processing/data_manager.py
  physical_ai_server/physical_ai_server/data_processing/lerobot_dataset_wrapper.py
  physical_ai_server/setup.py
  physical_ai_tools/CHANGELOG.rst
  physical_ai_tools/package.xml
Labels: bump

#44 Bump 0.5.13
  docker/docker-compose.yml
  physical_ai_interfaces/CHANGELOG.rst
  physical_ai_interfaces/package.xml
  physical_ai_manager/CHANGELOG.rst
  physical_ai_manager/package-lock.json
  physical_ai_manager/package.json
  physical_ai_server/CHANGELOG.rst
  physical_ai_server/package.xml
  physical_ai_server/setup.py
  physical_ai_tools/CHANGELOG.rst
  physical_ai_tools/package.xml
Labels: bump

#46 Fix Server Crashes Due to Incorrect Robot Type
  physical_ai_interfaces/CHANGELOG.rst
  physical_ai_interfaces/package.xml
  physical_ai_manager/CHANGELOG.rst
  physical_ai_manager/package-lock.json
  physical_ai_manager/package.json
  physical_ai_server/CHANGELOG.rst
  physical_ai_server/package.xml
  physical_ai_server/physical_ai_server/physical_ai_server.py
  physical_ai_server/setup.py
  physical_ai_tools/CHANGELOG.rst
  physical_ai_tools/package.xml
Labels: bug

#47 Bump 0.6.1
  physical_ai_interfaces/CHANGELOG.rst
  physical_ai_interfaces/package.xml
  physical_ai_manager/CHANGELOG.rst
  physical_ai_manager/package-lock.json
  physical_ai_manager/package.json
  physical_ai_server/CHANGELOG.rst
  physical_ai_server/package.xml
  physical_ai_server/physical_ai_server/physical_ai_server.py
  physical_ai_server/setup.py
  physical_ai_tools/CHANGELOG.rst
  physical_ai_tools/package.xml
Labels: bump

#50 Updated output dir to use absolute dir and bug fix
  docker/docker-compose.yml
  physical_ai_interfaces/CHANGELOG.rst
  physical_ai_interfaces/package.xml
  physical_ai_manager/CHANGELOG.rst
  physical_ai_manager/package-lock.json
  physical_ai_manager/package.json
  physical_ai_server/CHANGELOG.rst
  physical_ai_server/Dockerfile.arm64
  physical_ai_server/package.xml
  physical_ai_server/physical_ai_server/communication/communicator.py
  physical_ai_server/physical_ai_server/data_processing/data_manager.py
  physical_ai_server/physical_ai_server/physical_ai_server.py
  physical_ai_server/physical_ai_server/training/training_manager.py
  physical_ai_server/setup.py
  physical_ai_tools/CHANGELOG.rst
  physical_ai_tools/package.xml
Labels: enhancement

#51 Bump 0.6.3
  docker/docker-compose.yml
  physical_ai_interfaces/CHANGELOG.rst
  physical_ai_interfaces/package.xml
  physical_ai_manager/CHANGELOG.rst
  physical_ai_manager/package-lock.json
  physical_ai_manager/package.json
  physical_ai_server/CHANGELOG.rst
  physical_ai_server/Dockerfile.arm64
  physical_ai_server/package.xml
  physical_ai_server/physical_ai_server/communication/communicator.py
  physical_ai_server/physical_ai_server/data_processing/data_manager.py
  physical_ai_server/physical_ai_server/physical_ai_server.py
  physical_ai_server/physical_ai_server/training/training_manager.py
  physical_ai_server/setup.py
  physical_ai_tools/CHANGELOG.rst
  physical_ai_tools/package.xml
Labels: bump
