Repository ROBOTIS-GIT/physical_ai_tools, pull requests merged in 2025-06, with the labels that each got.

#23 Fixed control panel buttons not enabled/disabled correctly
  physical_ai_interfaces/CHANGELOG.rst
  physical_ai_interfaces/package.xml
  physical_ai_manager/CHANGELOG.rst
  physical_ai_manager/package-lock.json
  physical_ai_manager/package.json
  physical_ai_manager/src/pages/InferencePage.js
  physical_ai_manager/src/pages/RecordPage.js
  physical_ai_server/CHANGELOG.rst
  physical_ai_server/package.xml
  physical_ai_tools/CHANGELOG.rst
  physical_ai_tools/package.xml
Labels: enhancement

#24 Bump 0.5.5
  physical_ai_interfaces/CHANGELOG.rst
  physical_ai_interfaces/package.xml
  physical_ai_manager/CHANGELOG.rst
  physical_ai_manager/package-lock.json
  physical_ai_manager/package.json
  physical_ai_manager/src/pages/InferencePage.js
  physical_ai_manager/src/pages/RecordPage.js
  physical_ai_server/CHANGELOG.rst
  physical_ai_server/package.xml
  physical_ai_tools/CHANGELOG.rst
  physical_ai_tools/package.xml
Labels: bump

#25 Fixing numpy version issue in docker
  physical_ai_interfaces/CHANGELOG.rst
  physical_ai_interfaces/package.xml
  physical_ai_manager/CHANGELOG.rst
  physical_ai_manager/package-lock.json
  physical_ai_manager/package.json
  physical_ai_server/CHANGELOG.rst
  physical_ai_server/Dockerfile
  physical_ai_server/package.xml
  physical_ai_server/setup.py
  physical_ai_tools/CHANGELOG.rst
  physical_ai_tools/package.xml
Labels: bug
